name: main
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

# Add regular dependencies here.
dependencies:

dev_dependencies:
  domain:
    path: ../domain
  application:
    path: ../application
  adapters_inbound_rest:
    path: ../adapters-inbound/rest
  adapters_outbound_persistence:
    path: ../adapters-outbound/persistence
  shelf: ^1.4.0
  http: ^0.13.5
  lints: ^2.0.0
  test: ^1.21.0
